### ISSUE TITLE
Build issues on Ubuntu 15.04

### ISSUE THREAD

**Issue by bblackham** [alexmurray/replay#4]
Trying to build on Ubuntu 15.04 gives this error:

```
config.status: error: po/Makefile.in.in was not created by intltoolize
```
It seems to be the same issue as in this link below, and the same fix to configure.ac solves it:

https://mail.gnome.org/archives/commits-list/2013-August/msg10312.html

Next I hit this:
```
Making all in replay
make[1]: Entering directory '/home/b/replay/replay'
make  all-am
make[2]: Entering directory '/home/b/replay/replay'
  CC       libreplay_la-replay-application.lo
In file included from replay-application.c:24:0:
../replay/replay-window.h:102:1: error: unknown type name 'GtkUIManager'
 GtkUIManager *replay_window_get_ui_manager(ReplayWindow *self);
 ^
```

I had to remove -DGTK_DISABLE_DEPRECATED and add -Wno-deprecated-declarations to configure.ac.

With that I can now build and run replay. (I'd provide a patch, but I'm not convinced what I've done is the best approach!)

**Comment by alexmurray** [comment]
Thanks - I haven't had much of a look at replay for a while - these fixes seem reasonable for now. Certainly the first change to configure.ac for the intltoolize error seems like the right solution.
The other two probably need a 'real' solution (ie. code changes to not use the deprecated APIs) but that is a much bigger piece of work - feel free to submit a PR.
